#cloud-config
package_update: true
ssh_pwauth: true
hostname: ${node_name}

users:
  - name: ${ssh_user}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_public_key}

chpasswd:
  list: |
    ${ssh_user}:${ssh_password}
  expire: false

packages:
%{ for pkg in node_packages ~}
  - ${pkg}
%{ endfor ~}

write_files:
  - path: /usr/local/bin/k3s-shared-storage-setup.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      mkdir -p ${data_dir}
      echo "${nfs_server}:${nfs_path} ${data_dir} nfs defaults,_netdev 0 0" >> /etc/fstab
      mount -a

  - path: /usr/local/bin/k3s-worker-setup.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e
      KUBECONFIG_SRC="/etc/rancher/k3s/k3s-${cluster_name}-${cluster_id}.yaml"
      KUBECONFIG_DEST="$HOME/.kube/config"
      WAIT_INTERVAL=2

      echo "=== Setting up k3s config ==="
      mkdir -p /etc/rancher/k3s
      cat <<EOF > /etc/rancher/k3s/config.yaml
      node-name: $(hostname)
      EOF

      wait_for_kubeconfig() {
          echo "=== Waiting for kubeconfig ==="
          while [ ! -f "$KUBECONFIG_SRC" ]; do
              sleep "$WAIT_INTERVAL"
          done
      }

      setup_kubeconfig() {
          mkdir -p "$(dirname "$KUBECONFIG_DEST")"
          cp "$KUBECONFIG_SRC" "$KUBECONFIG_DEST"
      }

      echo "=== Waiting for kubeconfig ==="
      wait_for_kubeconfig
      setup_kubeconfig

      echo "=== Joining cluster ==="
      curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=${k3s_version} sh -s - agent --token=${k3s_token} --server https://${master_ip}:6443 ${install_flags} ${other_flags}

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - /usr/local/bin/k3s-worker-setup.sh
